apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-s3-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # <--- O segredo estÃ¡ aqui
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /flask/?(.*) # <--- Captura tudo que vem depois de /flask
        pathType: ImplementationSpecific
        backend:
          service:
            name: flask-s3-service
            port:
              number: 80
