apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-s3-ingress
  # Note que as annotations de rewrite sumiram!
spec:
  ingressClassName: nginx
  rules:
  - host: api-flask.54-81-241-46.sslip.io # Substitua pelo seu IP do sslip
    http:
      paths:
      - path: / # Agora o caminho volta a ser a raiz simples
        pathType: Prefix
        backend:
          service:
            name: flask-s3-service
            port:
              number: 80
