apiVersion: v1
kind: Service
metadata:
  name: flask-s3-service
spec:
  selector:
    app: flask-s3
  ports:
    - protocol: TCP
      port: 80        # Porta que você vai acessar no navegador
      targetPort: 5000 # Porta que o Flask está ouvindo dentro do Pod
  #type: LoadBalancer  # No EKS, isso cria um Classic Load Balancer da AWS automaticamente
  type: ClusterIP
